name: Test_Successful_Build
run-name: ${{ github.actor }} is testing the build
on: [push, pull_request]
jobs:
    testing_build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Say Hello
              run: echo "Hello World"
              shell: powershell
